version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - API_DEBUG=False
      - UI_HOST=0.0.0.0
      - UI_PORT=7860
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LLM_MODEL=gpt-4o
      - LLM_TEMPERATURE=0.7
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  ui:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7860:7860"
    environment:
      - API_HOST=api
      - API_PORT=8000
      - UI_HOST=0.0.0.0
      - UI_PORT=7860
    volumes:
      - .:/app
    command: python -m app.interface.ui
    depends_on:
      - api
